# Generated by Django 2.2.10 on 2021-01-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CariGrup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, verbose_name='ad')),
            ],
        ),
        migrations.CreateModel(
            name='CariKart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cari_kodu', models.CharField(max_length=30)),
                ('ad', models.CharField(max_length=200)),
                ('adres', models.CharField(max_length=200)),
                ('ilce', models.IntegerField()),
                ('sehir', models.IntegerField()),
                ('eposta', models.EmailField(max_length=254)),
                ('web_adresi', models.CharField(max_length=200)),
                ('aciklama', models.CharField(max_length=500)),
                ('acik_hesap_limiti', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('vergi_dairesi', models.CharField(max_length=50, null=True)),
                ('vergi_numarasi', models.IntegerField(null=True)),
                ('tc_kimlik_numarasi', models.IntegerField(null=True)),
                ('yetkili_adi', models.CharField(max_length=100, null=True)),
                ('aktif_pasif', models.CharField(choices=[('A', 'Aktif'), ('P', 'Pasif')], default='A', max_length=1)),
                ('cari_grup', models.ForeignKey(blank=True, null=True, on_delete=None, to='muhasebe.CariGrup', verbose_name='carigrup')),
            ],
        ),
    ]
