# Generated by Django 4.0.1 on 2022-01-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apicase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField(blank=True, default=0, null=True)),
                ('api_type', models.CharField(blank=True, default='0', max_length=500, null=True)),
                ('priority', models.CharField(blank=True, choices=[('p1', 'p1'), ('p2', 'p2'), ('p3', 'p3')], default='0', max_length=500, null=True)),
                ('Dependencies', models.CharField(blank=True, default='0', max_length=500, null=True)),
                ('Description', models.CharField(blank=True, default='0', max_length=500, null=True)),
                ('service_name', models.CharField(blank=True, default='0', max_length=500, null=True)),
                ('owner_poc', models.CharField(blank=True, default='0', max_length=500, null=True)),
                ('mock_link', models.CharField(blank=True, default='0', max_length=500, null=True)),
                ('curl', models.CharField(blank=True, default='0', max_length=500, null=True)),
                ('dependent_services', models.CharField(blank=True, default='0', max_length=500, null=True)),
                ('dependent_spoc', models.CharField(blank=True, default='0', max_length=500, null=True)),
                ('dev_status', models.CharField(blank=True, choices=[('dev in progress', 'dev in progress'), ('tbd', 'tbd'), ('finished', 'finished')], default='0', max_length=500, null=True)),
                ('open_q', models.CharField(blank=True, default='0', max_length=500, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'pending'), ('automated', 'automated'), ('automatable', 'automatable'), ('failed', 'failed'), ('blocked', 'blocked'), ('TBD', 'TBD'), ('NA', 'NA')], default='0', max_length=500, null=True)),
                ('test_owner', models.CharField(blank=True, default='0', max_length=500, null=True)),
                ('jira', models.CharField(blank=True, default='0', max_length=500, null=True)),
                ('i_comm', models.CharField(blank=True, default='0', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.CharField(db_column='Last*', max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('web', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('rating', models.CharField(choices=[('b', 'Bad'), ('a', 'Average'), ('e', 'Excellent')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TesT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField(blank=True, default=0, null=True)),
                ('d_s', models.CharField(blank=True, default='0', max_length=500, null=True)),
                ('pre_req', models.CharField(blank=True, default='0', max_length=500, null=True)),
                ('t_scenario', models.CharField(blank=True, default='0', max_length=500, null=True)),
                ('exp_result', models.CharField(blank=True, default='0', max_length=500, null=True)),
                ('exp_plat', models.CharField(blank=True, choices=[('api', 'api'), ('android', 'android'), ('web', 'web'), ('pwa', 'pwa'), ('ios', 'ios')], default='0', max_length=500, null=True)),
                ('a_exe', models.CharField(blank=True, choices=[('api', 'api'), ('android', 'android'), ('web', 'web'), ('pwa', 'pwa'), ('ios', 'ios')], default='0', max_length=500, null=True)),
                ('b_status', models.CharField(blank=True, choices=[('passed', 'passed'), ('failed', 'failed'), ('pending', 'pending'), ('blocked', 'blocked'), ('NA', 'NA')], default='0', max_length=500, null=True)),
                ('c_date', models.CharField(blank=True, default='0', max_length=500, null=True)),
                ('d_owner', models.CharField(blank=True, choices=[('Harish A', 'Harish A'), ('zilka mehta', 'zilka mehta')], default='0', max_length=500, null=True)),
                ('e_id', models.CharField(blank=True, default='0', max_length=500, null=True)),
                ('f_auto', models.CharField(blank=True, choices=[('pending', 'pending'), ('automated', 'automated'), ('automatable', 'automatable'), ('failed', 'failed'), ('blocked', 'blocked'), ('TBD', 'TBD'), ('NA', 'NA')], default='0', max_length=500, null=True)),
                ('g_aown', models.CharField(blank=True, default='0', max_length=500, null=True)),
                ('h_poc', models.CharField(blank=True, choices=[('Himanshu Nikhare', 'Himanshu Nikhare'), ('Rakesh Kumar', 'Rakesh Kumar')], default='0', max_length=500, null=True)),
                ('i_comm', models.CharField(blank=True, default='0', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Test Summary',
                'verbose_name_plural': 'Tests Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.test',),
        ),
    ]
